export const STORAGE_READ = 'STORAGE_READ'
export const STORAGE_WRITE = 'STORAGE_WRITE'
export const STORAGE_DELETE = 'STORAGE_DELETE'
export const STORAGE_CHANGED = 'STORAGE_CHANGED'

export const SETTINGS_READ = 'SETTINGS_READ'
// export const SETTINGS_WRITE = 'SETTINGS_WRITE'
export const SETTINGS_READ_ALL = 'SETTINGS_READ_ALL'
export const SETTINGS_WRITE_ALL = 'SETTINGS_WRITE_ALL'
export const SETTINGS_CHANGED = 'SETTINGS_CHANGED'

export const GET_OPTION_DEFS = 'GET_OPTION_DEFS'

export const PROXIED_FETCH_GET = 'PROXIED_FETCH_GET'
export const PROXIED_AUDIO = 'PROXIED_AUDIO'
export const PROXIED_CREATE_TAB = 'PROXIED_CREATE_TAB'
